package id.ac.itats.skripsi.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLACE.
 */
public class Place {

    private Long placeID;
    private String latLon;
    private String category;
    private String name;
    private String address;

    public Place() {
    }

    public Place(Long placeID) {
        this.placeID = placeID;
    }

    public Place(Long placeID, String latLon, String category, String name, String address) {
        this.placeID = placeID;
        this.latLon = latLon;
        this.category = category;
        this.name = name;
        this.address = address;
    }

    public Long getPlaceID() {
        return placeID;
    }

    public void setPlaceID(Long placeID) {
        this.placeID = placeID;
    }

    public String getLatLon() {
        return latLon;
    }

    public void setLatLon(String latLon) {
        this.latLon = latLon;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
