package id.ac.itats.skripsi.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROAD_PLACE.
 */
public class RoadPlace {

    private Long id;
    private Long fk_road;
    private Long fk_place;

    public RoadPlace() {
    }

    public RoadPlace(Long id) {
        this.id = id;
    }

    public RoadPlace(Long id, Long fk_road, Long fk_place) {
        this.id = id;
        this.fk_road = fk_road;
        this.fk_place = fk_place;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFk_road() {
        return fk_road;
    }

    public void setFk_road(Long fk_road) {
        this.fk_road = fk_road;
    }

    public Long getFk_place() {
        return fk_place;
    }

    public void setFk_place(Long fk_place) {
        this.fk_place = fk_place;
    }

}
