package id.ac.itats.skripsi.orm;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import id.ac.itats.skripsi.orm.RoadPlace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ROAD_PLACE.
*/
public class RoadPlaceDao extends AbstractDao<RoadPlace, Long> {

    public static final String TABLENAME = "ROAD_PLACE";

    /**
     * Properties of entity RoadPlace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fk_road = new Property(1, Long.class, "fk_road", false, "FK_ROAD");
        public final static Property Fk_place = new Property(2, Long.class, "fk_place", false, "FK_PLACE");
    };


    public RoadPlaceDao(DaoConfig config) {
        super(config);
    }
    
    public RoadPlaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ROAD_PLACE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'FK_ROAD' INTEGER," + // 1: fk_road
                "'FK_PLACE' INTEGER);"); // 2: fk_place
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ROAD_PLACE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RoadPlace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long fk_road = entity.getFk_road();
        if (fk_road != null) {
            stmt.bindLong(2, fk_road);
        }
 
        Long fk_place = entity.getFk_place();
        if (fk_place != null) {
            stmt.bindLong(3, fk_place);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RoadPlace readEntity(Cursor cursor, int offset) {
        RoadPlace entity = new RoadPlace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // fk_road
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // fk_place
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RoadPlace entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFk_road(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setFk_place(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RoadPlace entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RoadPlace entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
