package id.ac.itats.skripsi.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import id.ac.itats.skripsi.orm.Node;
import id.ac.itats.skripsi.orm.Way;

import id.ac.itats.skripsi.orm.NodeDao;
import id.ac.itats.skripsi.orm.WayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nodeDaoConfig;
    private final DaoConfig wayDaoConfig;

    private final NodeDao nodeDao;
    private final WayDao wayDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nodeDaoConfig = daoConfigMap.get(NodeDao.class).clone();
        nodeDaoConfig.initIdentityScope(type);

        wayDaoConfig = daoConfigMap.get(WayDao.class).clone();
        wayDaoConfig.initIdentityScope(type);

        nodeDao = new NodeDao(nodeDaoConfig, this);
        wayDao = new WayDao(wayDaoConfig, this);

        registerDao(Node.class, nodeDao);
        registerDao(Way.class, wayDao);
    }
    
    public void clear() {
        nodeDaoConfig.getIdentityScope().clear();
        wayDaoConfig.getIdentityScope().clear();
    }

    public NodeDao getNodeDao() {
        return nodeDao;
    }

    public WayDao getWayDao() {
        return wayDao;
    }

}
