package id.ac.itats.skripsi.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROAD.
 */
public class Road {

    private Long roadID;
    private String name;

    public Road() {
    }

    public Road(Long roadID) {
        this.roadID = roadID;
    }

    public Road(Long roadID, String name) {
        this.roadID = roadID;
        this.name = name;
    }

    public Long getRoadID() {
        return roadID;
    }

    public void setRoadID(Long roadID) {
        this.roadID = roadID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
